---
repos:
  - repo: https://github.com/python/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.11.5
    hooks:
      - id: isort
        args: ["--profile", "black"]