name: CI test
on:
  pull_request:
    branches: [main]
  push:
    branches: [main, test-ci]

# TODO: create a game
jobs:
  testbuild:
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Build Docker Container"
        run: |
          docker build --target test_ci --no-cache --tag ci_image .
      - name: "Run Tests"
        run: |
          docker run --rm ci_image
