name: CI test
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, test_CI ]

jobs:
  testbuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: | 
           docker build -f Dockerfile \
             --build-arg PYTHON_VERSION=3.7 \
             --tag baseline-bots-docker .