name: CI test
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, test_CI ]

jobs:
  testbuild:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Setup Python"
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: "Build"
      run: |
        pip install -r requirements.txt
        pip install -e .

    - name: "Run tests"
      run: |
        docker run --rm allan_test_env /bin/bash -c "pytest --ignore=tests/bot_tests/SOA_test.py --ignore=tests/randomize_order_test.py --ignore=tests/bot_tests/dipnet.py"
