name: CI test
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, test_CI ]

jobs:
  testbuild:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Setup Python"
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: "Build"
      run: |
        pip install -r requirements.txt
        pip install -e .

    - name: "Run tests"
      run: |
        pytest tests/utils_test.py
        pytest tests/bot_tests/bots_test.py
        pytest tests/randomize_order_test.py
