name: CI test
on:
  push:
    branches: [ main, test_CI ]

# TODO: create a game
jobs:
  testbuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pytest
        run: |
          pytest tests/utils_test.py
          # pytest tests/bot_tests/bots_test.py
          pytest tests/randomize_order_test.py
          # pytest tests/bot_tests/soa_bot_functions_test.py
      
      - name: TACC
        run: |
          wget https://f002.backblazeb2.com/file/ppaquette-public/benchmarks/neurips2019-sl_model.zip
          mkdir bot_neurips2019-sl_model
          unzip neurips2019-sl_model.zip -d bot_neurips2019-sl_model/
          docker build -t allan_test_env .
          docker run allan_test_env