name: CI test
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, test_CI ]

# TODO: create a game
jobs:
  testbuild:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Setup Python"
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      
      - name: "Build Docker Container"
        run: |
          docker build --no-cache -t ci_image .

      - name: "Run Tests"
        run: |
          docker run --rm ci_image /bin/bash -c "/model/src/model_server/baseline_bots/containers/allan_dip_bot/run_model_server.sh & \
          ENV_NAME='ASYNC_TEST_TIMEOUT' ENV_NUMBER='180' pytest"
